services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8180/api/v1
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - frontend_cache:/app/.vite
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - dev-network

  backend:
    image: golang:1.24-alpine
    working_dir: /app
    ports:
      - "8180:8180"
    env_file:
      - config/dev/.env
    environment:
      - APP_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - go_cache:/go/pkg/mod
    command: sh -c "go install github.com/air-verse/air@latest && air"
    networks:
      - dev-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8180/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5434:5432"
    env_file:
      - config/dev/.env
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d vocab_dev -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    env_file:
      - config/dev/.env
    volumes:
      - redis_data:/bitnami/redis
    networks:
      - dev-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "dev_redis_password_456", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:
  redis_data:
  go_cache:
  frontend_cache:

networks:
  dev-network:
    driver: bridge
    name: vocab-trainer-dev
