services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8090:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app

  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "54321:5432"
    environment:
      POSTGRESQL_USERNAME: user
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: vocab
    volumes:
      - postgres_data:/bitnami/postgresql
    restart: always

  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_USERNAME: redis
      REDIS_PASSWORD: redis_password
    volumes:
      - redis_data:/bitnami/redis

volumes:
  postgres_data:
  redis_data:
