openapi: 3.0.0
info:
  title: English Vocabulary Trainer API
  version: 1.0.0
servers:
  - url: http://localhost:8180/api/v1
paths:
  /register:
    post:
      summary: Register a new user
      tags: [auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Registered user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Bad request

  /login:
    post:
      summary: Login with username and password
      tags: [auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Authenticated user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: Unauthorized

  /session:
    post:
      summary: Create a new session tag
      description: Sets an HttpOnly cookie named `session_tag` and returns its value.
      tags: [auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [user_id, level_id]
              properties:
                user_id:
                  type: integer
                  format: int64
                level_id:
                  type: integer
                  format: int64
      responses:
        "200":
          description: Session tag created
          headers:
            Set-Cookie:
              description: "Sets session_tag cookie (HttpOnly)"
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionResponse"

  /levels:
    get:
      summary: List available levels
      tags: [levels]
      responses:
        "200":
          description: List of levels
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Level"

  /words/random:
    get:
      summary: Get random words by language and difficulty
      tags: [words]
      parameters:
        - in: query
          name: count
          required: true
          schema:
            type: integer
            minimum: 1
        - in: query
          name: language
          required: true
          schema:
            type: string
            example: en
        - in: query
          name: difficulty
          required: true
          schema:
            type: string
            enum: [easy, medium, hard]
        - in: query
          name: cursor
          required: false
          description: Stateless cursor to avoid duplicate words in subsequent requests
          schema:
            type: string
      responses:
        "200":
          description: Random words and pagination cursor
          content:
            application/json:
              schema:
                type: object
                properties:
                  words:
                    type: array
                    items:
                      $ref: "#/components/schemas/Word"
                  next_cursor:
                    type: string
                    nullable: true
        "400":
          description: Invalid parameters

  /history/{userID}:
    get:
      summary: Get play history for a user
      tags: [history]
      parameters:
        - in: path
          name: userID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: List of play entries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/HistoryEntry"
        "400":
          description: Invalid user id

  /answer:
    post:
      summary: Submit an answer and get the correct translation
      description: Requires the `session_tag` cookie set by POST /session.
      tags: [game]
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AnswerRequest"
      responses:
        "200":
          description: Result of the submitted answer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnswerResponse"
        "400":
          description: Invalid request (missing session_tag or bad input)

  /finish:
    post:
      summary: Mark current session as finished
      description: Requires the `session_tag` cookie set by POST /session.
      tags: [game]
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Session marked as finished
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: finished
        "400":
          description: Missing or invalid session_tag

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session_tag
  schemas:
    User:
      type: object
      properties:
        user_id:
          type: integer
          format: int64
        username:
          type: string
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time

    Word:
      type: object
      properties:
        word_id:
          type: integer
          format: int64
        concept_id:
          type: string
          format: uuid
        language_code:
          type: string
          example: en
        word_text:
          type: string
          example: apple
        difficulty:
          type: string
          enum: [easy, medium, hard]
        is_primary:
          type: boolean

    Play:
      type: object
      properties:
        play_id:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64
        word_id:
          type: integer
          format: int64
        user_answer:
          type: string
        is_correct:
          type: boolean
        score:
          type: integer
        target:
          type: integer
        played_at:
          type: string
          format: date-time
        session_tag:
          type: string
          format: uuid

    Session:
      type: object
      properties:
        session_tag:
          type: string
          format: uuid
        started_at:
          type: string
          format: date-time

    HistoryEntry:
      type: object
      properties:
        play_id:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64
        user_answer:
          type: string
        is_correct:
          type: boolean
        score:
          type: integer
        target:
          type: integer
        played_at:
          type: string
          format: date-time
        session:
          $ref: "#/components/schemas/Session"
        word:
          $ref: "#/components/schemas/Word"

    AnswerRequest:
      type: object
      required:
        - word_id
        - user_id
        - language_code
        - user_answer
      properties:
        word_id:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64
        language_code:
          type: string
          example: vi
        user_answer:
          type: string

    AnswerResponse:
      type: object
      properties:
        correct_answer:
          type: string
        is_correct:
          type: boolean
        score:
          type: integer
        target:
          type: integer
        total_score:
          type: integer

    SessionResponse:
      type: object
      properties:
        session_tag:
          type: string
          format: uuid

    Level:
      type: object
      properties:
        level_id:
          type: integer
          format: int64
        code:
          type: string
        name:
          type: string
        description:
          type: string
        difficulty:
          type: string
        scoring_config:
          type: object
          properties:
            target:
              type: integer
            target_rules:
              type: object
              properties:
                correct_bonus:
                  type: integer
                wrong_penalty:
                  oneOf:
                    - type: integer
                    - type: string
                mode:
                  type: string
                  enum: [number, formula]
              required:
                - correct_bonus
                - wrong_penalty
                - mode
              additionalProperties: false
            score_rules:
              type: object
              properties:
                correct_points:
                  type: integer
                wrong_penalty:
                  type: integer
              required:
                - correct_points
                - wrong_penalty
              additionalProperties: false
          required:
            - target
            - target_rules
            - score_rules
          additionalProperties: false
