openapi: 3.0.0
info:
  title: Vocabulary Learning App API
  version: 1.0.0
paths:
  /api/v1/words:
    get:
      summary: Get a list of words
      responses:
        '200':
          description: A list of words
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Word'
components:
  schemas:
    Word:
      type: object
      properties:
        id:
          type: integer
          format: int64
        word:
          type: string
        pronunciation:
          type: string
        definition:
          type: string
        part_of_speech:
          type: string
        example:
          type: string
        created_at:
          type: string
          format: date-time
