env: "development"

http:
  addr: ":8180"

postgres:
  host: "postgres"
  port: "5432"
  user: "dev_user"
  password: "dev_password_123"
  database: "vocab_dev"

redis:
  addr: "redis:6379"
  username: "default"
  password: "dev_redis_password_456"
  pool_size: 5
  min_idle_conns: 2

cursor:
  secret: "dev-super-secret-jwt-key-for-development-only-not-for-production"

deepl:
  apikey: "82aa2c21-9d7b-49c6-9149-7382172e07cd:fx"

jwt:
  secret: "dev-super-secret-jwt-key-for-development-only-not-for-production"

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:5173"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:5173"

rate_limit:
  requests_per_minute: 100

security:
  bcrypt_cost: 8
  session_timeout: "24h"
  cookie_secure: false
  cookie_http_only: true
  cookie_same_site: "lax"

database:
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "300s"

monitoring:
  enable_metrics: false
  metrics_port: 9100

health:
  timeout: "30s"
  interval: "1m"

log:
  level: "debug"

jobs:
  universe_index:
    enabled: true
    schedule: "0 2 * * *"  # 2:00 AM daily
  translate_missing:
    enabled: true
    schedule: "0 * * * *"  # Every hour
    batch_size: 50
